baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'A handbook on Data Structures and Algorithms'
theme = 'hugo-book'

enableGitInfo = true

[params]
  BookSection = "entries"
  BookSearch = true
  BookComments = false
  BookTheme = "auto"
  BookRepo = "https://github.com/csi-dsa/csi-dsa"
